name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build mobile project
      run: ./gradlew :mobile:assembleDebug
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: mobile-debug.apk
        path: ./mobile/build/outputs/apk/debug/mobile-debug.apk
